apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
data:  
  mysql-root-password: UGhvNXdlZVBoOVJhaDdhZQ== 
  mysql-user: Z29sZW0= 
  mysql-database: Z29sZW0=
  mysql-password: UmEyT3ppMW9ocjdqYWlRdTFFaQ==
